version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://root:wR7JNomv5hyKgyFLTNxqTjgm@annapurna.liara.cloud:34389/postgres
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - DEEPSEEK_API_KEY=sk-3fd6eff6b6f743e29533638c6fbcb9a1
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: wR7JNomv5hyKgyFLTNxqTjgm
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
